# Generated by Django 3.2.9 on 2021-12-09 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GREENHOUSE',
            fields=[
                ('Serial_id', models.AutoField(primary_key=True, serialize=False)),
                ('Gh_no', models.IntegerField(blank=True, default=1)),
            ],
            options={
                'db_table': 'GreenHouse',
            },
        ),
        migrations.CreateModel(
            name='ESP',
            fields=[
                ('Serial_id', models.AutoField(primary_key=True, serialize=False)),
                ('Esp_id', models.IntegerField(blank=True)),
                ('Esp_name', models.CharField(max_length=50)),
                ('Status', models.IntegerField(blank=True, default=0)),
                ('GH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Esp_sensor', to='espsensor.greenhouse')),
            ],
            options={
                'db_table': 'Esp',
            },
        ),
    ]
