# Generated by Django 3.2.9 on 2021-12-06 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ESP',
            fields=[
                ('esp_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('serial_id', models.AutoField(primary_key=True, serialize=False)),
                ('temp_degree', models.FloatField(blank=True, default=0, null=True)),
                ('esp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espsensor.esp')),
            ],
        ),
        migrations.CreateModel(
            name='SOIL',
            fields=[
                ('serial_id', models.AutoField(primary_key=True, serialize=False)),
                ('soil_degree', models.FloatField(blank=True, default=0, null=True)),
                ('soil_no', models.IntegerField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('esp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil', to='espsensor.esp')),
            ],
        ),
        migrations.CreateModel(
            name='LIGHT',
            fields=[
                ('serial_id', models.AutoField(primary_key=True, serialize=False)),
                ('light_degree', models.FloatField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('esp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='light', to='espsensor.esp')),
            ],
        ),
    ]
