# Generated by Django 3.2.9 on 2021-12-09 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('espsensor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SOIL',
            fields=[
                ('Serial_id', models.AutoField(primary_key=True, serialize=False)),
                ('Soil_degree', models.FloatField(blank=True, default=0, null=True)),
                ('Soil_no', models.IntegerField(blank=True, default=0, null=True)),
                ('Created', models.DateTimeField(auto_now_add=True, null=True)),
                ('EspSerial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil', to='espsensor.esp')),
            ],
            options={
                'db_table': 'soil',
            },
        ),
    ]
