# Generated by Django 3.2.9 on 2021-12-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espsensor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esp',
            name='esp_id',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
    ]
