# Generated by Django 3.2.9 on 2021-12-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espsensor', '0002_alter_esp_esp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='esp',
            name='GH_no',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
