# Generated by Django 3.2.9 on 2021-12-09 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('espsensor', '0003_sensorlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensorlist',
            old_name='SoilMoistureSensor',
            new_name='SoilMoistureSensor1',
        ),
    ]
