# Generated by Django 3.2.9 on 2021-12-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espsensor', '0004_rename_soilmoisturesensor_sensorlist_soilmoisturesensor1'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorlist',
            name='Topic',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
