# Generated by Django 3.2.9 on 2021-12-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espsensor', '0005_sensorlist_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorlist',
            name='SoilMoistureSensor2',
            field=models.FloatField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='sensorlist',
            name='SoilMoistureSensor1',
            field=models.FloatField(blank=True, default=1),
        ),
    ]
