# Generated by Django 3.2.9 on 2021-12-12 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('espsensor', '0006_auto_20211212_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorlist',
            name='LightSensor',
            field=models.FloatField(blank=True, default=-1),
        ),
        migrations.AlterField(
            model_name='sensorlist',
            name='SoilMoistureSensor1',
            field=models.FloatField(blank=True, default=-1),
        ),
        migrations.AlterField(
            model_name='sensorlist',
            name='SoilMoistureSensor2',
            field=models.FloatField(blank=True, default=-1),
        ),
        migrations.CreateModel(
            name='LIGHT',
            fields=[
                ('Serial_id', models.AutoField(primary_key=True, serialize=False)),
                ('Light_degree', models.FloatField(blank=True, default=0, null=True)),
                ('Created', models.DateTimeField(auto_now_add=True, null=True)),
                ('EspSerial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='light', to='espsensor.esp')),
            ],
            options={
                'db_table': 'light',
            },
        ),
    ]
