# Generated by Django 3.2.9 on 2021-12-12 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('espsensor', '0008_auto_20211212_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='air',
            old_name='pm25_degree',
            new_name='Pm25_degree',
        ),
        migrations.AddField(
            model_name='sensorlist',
            name='TempSensor',
            field=models.FloatField(blank=True, default=-1, null=True),
        ),
        migrations.CreateModel(
            name='TEMP',
            fields=[
                ('Serial_id', models.AutoField(primary_key=True, serialize=False)),
                ('Temp_degree', models.FloatField(blank=True, default=0, null=True)),
                ('Created', models.DateTimeField(auto_now_add=True, null=True)),
                ('EspSerial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp', to='espsensor.esp')),
            ],
            options={
                'db_table': 'temp',
            },
        ),
    ]
