# Generated by Django 3.2.9 on 2021-12-12 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('espsensor', '0009_auto_20211212_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorlist',
            name='HumiSensir',
            field=models.FloatField(blank=True, default=-1, null=True),
        ),
        migrations.CreateModel(
            name='HUMI',
            fields=[
                ('Serial_id', models.AutoField(primary_key=True, serialize=False)),
                ('Humi_degree', models.FloatField(blank=True, default=0, null=True)),
                ('Created', models.DateTimeField(auto_now_add=True, null=True)),
                ('EspSerial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='humi', to='espsensor.esp')),
            ],
            options={
                'db_table': 'humi',
            },
        ),
    ]
