# Generated by Django 3.2.9 on 2021-12-12 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('espsensor', '0010_auto_20211212_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorlist',
            name='CO2',
            field=models.FloatField(blank=True, default=-1, null=True),
        ),
        migrations.CreateModel(
            name='CO2',
            fields=[
                ('Serial_id', models.AutoField(primary_key=True, serialize=False)),
                ('Co2_degree', models.FloatField(blank=True, default=0, null=True)),
                ('Created', models.DateTimeField(auto_now_add=True, null=True)),
                ('EspSerial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co2', to='espsensor.esp')),
            ],
            options={
                'db_table': 'co2',
            },
        ),
    ]
