# Generated by Django 3.2.9 on 2021-12-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espsensor', '0015_auto_20211214_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorlist',
            name='SoilMoistureSensor1',
            field=models.FloatField(blank=True, choices=[('1', 'Active'), ('-1', 'Disable')], default='1'),
        ),
    ]
