# Generated by Django 3.2.9 on 2021-12-14 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('espsensor', '0017_auto_20211214_2156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensorlist',
            old_name='CO2',
            new_name='CO2Sensor',
        ),
    ]
