# Generated by Django 3.2.9 on 2021-12-19 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espsensor', '0018_rename_co2_sensorlist_co2sensor'),
    ]

    operations = [
        migrations.CreateModel(
            name='MQTT',
            fields=[
                ('Serial_id', models.AutoField(primary_key=True, serialize=False)),
                ('Fan', models.BooleanField(blank=True, default=0)),
            ],
            options={
                'db_table': 'mqtt',
            },
        ),
    ]
