# Generated by Django 4.0.1 on 2022-01-10 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('espsensor', '0019_mqtt'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='esp',
            table='esp',
        ),
        migrations.AlterModelTable(
            name='greenhouse',
            table='greenhouse',
        ),
        migrations.AlterModelTable(
            name='sensorlist',
            table='sensorlist',
        ),
    ]
