# Generated by Django 4.0.1 on 2022-03-09 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('espsensor', '0020_alter_esp_table_alter_greenhouse_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esp',
            name='Esp_id',
        ),
    ]
