# Generated by Django 4.0.1 on 2022-03-09 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('espsensor', '0022_remove_sensorlist_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorlist',
            name='GH',
        ),
    ]
